name: CI

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1', '8.2']
        include:
          - php-version: '8.3'
            flags: "--ignore-platform-req=php"
            stability: prefer-stable

    name: PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
              composer -V
              composer update --prefer-dist --no-interaction --no-progress ${{ matrix.flags }}
      - name: Execute tests
        run: ./vendor/bin/phpunit
